### PR TITLE
Polymorphism improvements

### PR DESCRIPTION
**Pull request by leo-naeka**
OK @ograycode, so here are some improvements.

My goal was to clearly separate regular and polymorphic serializers, as well as regular and polymorphic relations.
The downside of this is that serializers polymorphic relations requires to be explicitly declared (at this time) and this can be... quite verbose (see [example/serializers.py#L117-L118](https://github.com/ZeroCater/django-rest-framework-json-api/blob/c96383914c40b71bc8bdbc2d03d17dea7f797e55/example/serializers.py#L117-L118))...

This definitely needs some extra tests and above all, documentation.
I let you play with that, keep me informed!

### CODE REVIEW

**Comment by ograycode** [comment]
@leo-naeka thanks for doing this, looks like you may have solved some of the issues (like pulling out a generic polymorphic serializer and maybe solving the django <= 1.7 issue). What sort of tests do you suggest for it?

**Comment by leo-naeka** [comment]
Hey @ograycode, what's up about this?
What do you think about merging this to get it upstream? Then, more people could be able to test and make suggestions.

**Comment by ograycode** [comment]
@leo-naeka I wasn't sure if you were done with it or not.

**Comment by leo-naeka** [comment]
@ograycode Everything may not be completely finished, but at this time, I suppose the best approach is to get some feedback from people awaiting this upstream.
If anyone (including me) have something new to implement, we'll make other pull requests ;-)

**Pull request merged**
